medlemssys/api/urls.py
from django.conf.urls import url, include
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework.routers import DefaultRouter

from medlemssys.api import views


router = DefaultRouter()
router.register(r'medlem', views.MedlemViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'innmelding', views.medlem_innmelding, name='api-innmelding'),
    url(r'token', obtain_auth_token),
]

medlemssys/config/urls.py
# -*- coding: utf-8 -*-
# Copyright 2009-2016 Odin Hørthe Omdal

# This file is part of Medlemssys.

# Medlemssys is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Medlemssys is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with Medlemssys.  If not, see <http://www.gnu.org/licenses/>.
from __future__ import unicode_literals

import django.contrib.auth.views
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

import medlemssys.api.urls as api_urls
import medlemssys.giro.admin_views as giro_admin
import medlemssys.innhenting.views as innhenting
import medlemssys.medlem.lokallag as lokallag
import medlemssys.medlem.views as medlem
import medlemssys.statistikk.admin_views as statistikk_admin
import medlemssys.statistikk.views as statistikk

urlpatterns = [
    url(r'^$',
        TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^robots.txt$',
        TemplateView.as_view(template_name='pages/robots.txt'), name='robots'),

    url(r'^admin/innhenting/import_ocr/',
        innhenting.import_ocr, name='import_ocr'),
    url(r'^admin/medlem/giro/send/', giro_admin.send, name='giro_send'),
    url(r'^admin/medlem/giro/manual/',
        giro_admin.manual_girosearch, name='giro_manual'),
    url(r'^admin/medlem/giro/gaaver/', giro_admin.gaaver, name='giro_gaaver'),
    url(r'^admin/revisions/',
        statistikk_admin.show_revisions, name='show_revisions'),
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    url(r'^accounts/login/$',
        django.contrib.auth.views.login, { 'template_name': 'login.html' }),
    url(r'^accounts/logout/$',
        django.contrib.auth.views.logout, { 'next_page': '/' }),
    url(r'^medlem/opprett', medlem.create_medlem),
    url(r'^medlem/(?P<id>\d+)/endra/(?P<nykel>\w+)',
        medlem.edit_medlem, name='medlem_edit'),
    url(r'^medlem/ringjelister', medlem.ringjelister),
    url(r'^lokallag/$', lokallag.home),
    url(r'^lokallag/(?P<slug>[-\w]+)/$',
        lokallag.lokallag_home, name='lokallag_home'),
    url(r'^takk', TemplateView.as_view(template_name='takk.html')),
    url(r'^stats/vervetopp/', statistikk.vervetopp),
    url(r'^stats/vervometer/', statistikk.vervometer),
    url(r'^member/search/', medlem.search, name='search'),
    url(r'^api/get_members.json',
        medlem.get_members_json, name='get_members_json'),
    url(r'^api/', include(api_urls), name='api-root'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    try:
        import debug_toolbar
        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]
    except:
        pass
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

medlemssys/urls.py
# -*- coding: utf-8 -*-
# Copyright 2009-2016 Odin Hørthe Omdal

# This file is part of Medlemssys.

# Medlemssys is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Medlemssys is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with Medlemssys.  If not, see <http://www.gnu.org/licenses/>.
import django.views.static
from django.conf import settings
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin
from django.views.generic.base import TemplateView

import giro.admin_views
import innhenting.views
import medlem.lokallag
import medlem.views
import statistikk.admin_views
import statistikk.views


admin.autodiscover()

urlpatterns = [
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', django.views.static.serve,
            {'document_root': '/home/odin/Kode/medlemssys/static'}),
    ]

medlem/models.py
# -*- coding: utf-8 -*-
# vim: ts=4 sts=4 expandtab ai
import random
from datetime import date, datetime
from django.conf import settings
from django.contrib.auth.models import User
from django.core.exceptions import ImproperlyConfigured
from django.core.urlresolvers import reverse
from django.db import models, transaction
from django.forms import ModelForm
from django.template.defaultfilters import slugify
from django.utils.importlib import import_module
from django.utils.translation import ugettext_lazy as _
#from emencia.django.newsletter.mailer import mailing_started

import mod10


def generate_password(length=7):
    return ''.join(random.choice('abcdefghjkmnpqrstuvwxyz23456789') for x in range(length))

class Val(models.Model):
    tittel = models.CharField(_("kort forklaring"), max_length=100, unique=True)
    forklaring = models.TextField(_("lang forklaring"), blank=True)

    @property
    def namn(self):
        return self.tittel

    class Meta:
        verbose_name_plural = "val"

    def __unicode__(self):
        return self.tittel

class Lokallag(models.Model):
    namn = models.CharField(_("namn"), max_length=255, unique=True)
    slug = models.SlugField(_("nettnamn"), max_length=255, unique=True, blank=True)
    kommunes = models.CharField(_("kommunar"), max_length=255, blank=True,
                   help_text="""Kommaseparert med stor forbokstav, t.d. "Stavanger, Sandnes".""")
    fylke = models.CharField(_("fylke"), max_length=255, blank=True,
                   help_text="""Berre eitt fylke, stor forbokstav. Overstyrer kommuner visst denne finst.""")
    andsvar = models.CharField(_("andsvar"), max_length=255, blank=True)
    lokalsats = models.IntegerField(_("lokalsats"), default=0)

    aktivt = models.BooleanField(_("aktivt"), default=True)
    epost = models.EmailField(_("epost"), blank=True,
        help_text=_(u"""Eiga epostliste til styret. Tek prioritet
        over å senda enkeltvis til dei som er registrert som styre."""))

    class Meta:
        verbose_name_plural = "lokallag"
        ordering = ['-aktivt', 'namn']

    def num_medlem(self):
        return self.medlem_set.betalande().count()
    num_medlem.short_description = "medlemstal"

    def listing(self):
        return reverse('lokallag_home', args=(self.slug,))

    def styreepostar(self):
        if self.epost:
            return [self.epost]
        return self.rollemedlem.exclude(epost='').values_list('epost', flat=True)

    def styret(self):
        return self.rolle_set.all()

    def styret_admin(self):
        styret = [u"{} ({})".format(x.medlem.admin_change(), x.rolletype) for x in self.styret()]
        return u', '.join(styret)
    styret_admin.short_description = _("Styret")
    styret_admin.allow_tags = True

    def save(self, *args, **kwargs):
        if not self.slug or self.slug == "":
            self.slug = slugify(self.namn)
        super(Lokallag, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return self.listing()

    def __unicode__(self):
        return self.namn

class Innmeldingstype(models.Model):
    namn = models.CharField(_("namn"), max_length=255, unique=True)

    class Meta:
        verbose_name_plural = "innmeldingstypar"

    def __unicode__(self):
        return self.namn


STATUSAR = (
    ("M", "Vanleg medlem"),
    ("I", "Infoperson"),
    ("L", "Livstidsmedlem"),
)

INNMELDINGSTYPAR = (
    ("H", "Heimesida"),
    ("M", "Målferd"),
    ("V", "Vervekampanje"),
    ("F", "Flygeblad"),
    ("L", "Lagsskiping/årsmøte"),
    ("D", "Direkteverva"),
    ("S", "SMS"),
    ("O", "Vitjing"),
    ("A", "Anna"),
    ("U", "--"),
)


class MedlemManager(models.Manager):
    def get_query_set(self):
        mod_name = settings.BEHAVIOUR_MODULE
        mod = import_module(mod_name)
        try:
            klass = getattr(mod, 'MedlemQuerySet')
        except AttributeError:
            raise ImproperlyConfigured(
                'Behaviour module "{0}" does not define a '
                '"MedlemQuerySet" class'.format(mod_name))
        return klass(self.model)

    def __getattr__(self, attr, *args):
        if attr.startswith("_"):
            raise AttributeError
        return getattr(self.get_query_set(), attr, *args)


class Medlem(models.Model):
    fornamn = models.CharField(_("fornamn"), max_length=255)
    mellomnamn = models.CharField(_("mellomnamn"), max_length=255,
            blank=True)
    etternamn = models.CharField(_("etternamn"), max_length=255)
    fodt = models.IntegerField(_(u"født"), max_length=4,
            blank=True, null=True)
    # Hadde denne før, men importering gjorde folk so gamle då: default=date.today().year - 17,

    # Kontakt
    postnr = models.CharField(
        _("postnr"), max_length=4,
        help_text="'0000' viss norsk adresse manglar")
    epost = models.CharField(_("epost"), max_length=255,
            blank=True)
    postadr = models.CharField(
        _("postadresse"), max_length=255, blank=True, null=True,
        help_text="Skriv utanlands-/skuleadresse i borte-addresse")
    ekstraadr = models.CharField(_("ekstraadresse"), max_length=255,
            blank=True)
    mobnr = models.CharField(_("mobiltelefon"), max_length=50,
            blank=True)
    heimenr = models.CharField(_("heimetelefon"), max_length=50,
            blank=True)

    bortepostnr = models.CharField(
            _("borte-postnr"), max_length=255, blank=True, null=True,
            help_text="T.d. '0864' eller 'c/o John Smith, 50012 OX-5, Oxford England'")
    borteadr = models.CharField(
            _("borte-adresse"), max_length=255, blank=True, null=True,
            help_text="Dersom borte-adressene er sett, vert post sendt her. For t.d. hybel- og utenlandsadresser.")

    # Om medlemen
    gjer = models.CharField(_("gjer"), max_length=255,
        blank=True)
    kjon = models.CharField(_("kjønn"), max_length=1, choices=(("M", "Mann"),
        ("K", "Kvinne"), ("U", "Udefinert")), default="U")
    merknad = models.TextField(_("merknad"), blank=True, default="")

    # Spesialfelt, denormalisert felt frå Giro
    _siste_medlemspengar = models.PositiveIntegerField(blank=True, null=True,
            editable=False, default=None)

    # Medlemsskapet
    innmeldt_dato = models.DateField(_("innmeldt"), default=date.today)
    utmeldt_dato = models.DateField(_("utmeldt"), blank=True, null=True,
            default=None)
    status = models.CharField(_("medlstatus"), max_length=1,
            choices=STATUSAR, default="M")
    innmeldingstype = models.CharField(_("innmtype"), max_length=1,
            choices=INNMELDINGSTYPAR, default='U')
    innmeldingsdetalj = models.CharField(_("detalj om innmelding"), max_length=255,
        blank=True, help_text=_("Skriv inn vervemedlem i hakeparantesar ([1234])"))
    verva_av = models.ForeignKey('Medlem', related_name='har_verva', blank=True, null=True)
    betalt_av = models.ForeignKey('Medlem', related_name='betalar_for', blank=True, null=True)

    # Tilkopla felt
    lokallag = models.ForeignKey(Lokallag,
        blank=True, null=True, on_delete=models.SET_NULL)
    val = models.ManyToManyField(Val, blank=True, null=True)
    lokallagsrolle = models.ManyToManyField(Lokallag,
        through='Rolle', related_name="rollemedlem", blank=True, null=True)

    user = models.OneToOneField(User, verbose_name=_("innloggingsbrukar"),
                                blank=True, null=True)
    oppretta = models.DateTimeField(_("oppretta"), auto_now_add=True)
    oppdatert = models.DateTimeField(_("oppdatert"), auto_now=True)
    nykel = models.CharField(_("nykel"), max_length=255,
            blank=True, default=generate_password)

    @property
    def stad(self):
        try:
            return PostNummer.objects.get(postnr=self.postnr).poststad
        except PostNummer.DoesNotExist:
            return "?"

    @property
    def bortestad(self):
        try:
            return PostNummer.objects.get(postnr=self.bortepostnr).poststad
        except PostNummer.DoesNotExist:
            return "?"

    @property
    def bukommune(self):
        postnr = self.bortepostnr or self.postnr
        try:
            return PostNummer.objects.get(postnr=postnr).kommune
        except PostNummer.DoesNotExist:
            return "?"

    @property
    def bufylke(self):
        postnr = self.bortepostnr or self.postnr
        try:
            return PostNummer.objects.get(postnr=postnr).fylke
        except PostNummer.DoesNotExist:
            return "?"

    # Managers
    objects = MedlemManager()

    class Meta:
        verbose_name_plural = "medlem"
        ordering = ['-id']

    def __unicode__(self):
        return " ".join([ x for x in [self.fornamn, self.mellomnamn, self.etternamn] if x ])
    __unicode__.admin_order_field = 'etternamn'

    def get_absolute_url(self):
        return reverse('medlem_edit', args=(self.pk, self.nykel))

    def er_innmeldt(self):
        if (self.utmeldt_dato):
            return self.utmeldt_dato > date.today()
        return True
    er_innmeldt.short_description = _("Innmeld")
    er_innmeldt.boolean = True

    def er_teljande(self):
        return self.fodt > (date.today().year - 26)
    er_teljande.short_description = _("Teljande")
    er_teljande.boolean = True

    def er_gamal(self):
        return self.fodt < (date.today().year - 23)
    er_teljande.short_description = _("Gamal")
    er_teljande.boolean = True

    def alder(self):
        if not self.fodt:
            return None
        alder = date.today().year - self.fodt
        if alder >= 0 and alder < 120:
            return alder
        return None

    def pronomen(self):
        if self.kjon == 'M':
            return "han"
        elif self.kjon == 'K':
            return "ho"
        return "ho/han"

    def fodt_farga(self):
        if self.alder() == None:
            return "?"
        if not self.er_teljande():
            return "<span class='ikkje-teljande' title='Medlemen er ikkje " + \

medlemssys/api/views.py
# -*- coding: utf-8 -*-
# vim: ts=4 sts=4 expandtab ai

# Copyright 2009-2016 Odin Hørthe Omdal

# This file is part of Medlemssys.

# Medlemssys is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Medlemssys is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with Medlemssys.  If not, see <http://www.gnu.org/licenses/>.

from __future__ import unicode_literals

from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from rest_framework import status
from rest_framework import viewsets
from rest_framework.decorators import api_view
from rest_framework.decorators import permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

from medlemssys.api import serializers
from medlemssys.medlem import models as medlem_models
from medlemssys.utils import add_cors
from medlemssys.utils import add_next_redirect


@csrf_exempt
@add_cors
@add_next_redirect
@api_view(['POST'])
@permission_classes((AllowAny,))
def medlem_innmelding(request):
    serializer = serializers.InnmeldingMedlemSerializer(data=request.data)
    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data, status=status.HTTP_201_CREATED)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class MedlemViewSet(viewsets.ModelViewSet):
    queryset = medlem_models.Medlem.objects.all()
    serializer_class = serializers.MedlemSerializer

medlemssys/templates/medlem/create.html
{% extends "base.html" %}

{% block content %}
<form method="post" action="">
    <table>
        {{ form }}
    </table>
    <input type="submit">
</form>
{% endblock %}

medlemssys/templates/medlem/edit.html
{% extends "base.html" %}
{% load utils %}

{% block header %}{% endblock %}
{% block content %}
<style>
#id_epost, #id_postadr, #id_borteadr { width: 96% }
#id_postnr, #id_fodt, #id_bortepostnr { width: 5em; }
#id_mobnr { width: 8em; }
.helptext { font-size: 0.8em; color: #666; }
</style>
<div style="max-width: 802px; margin: 0 auto; box-shadow: 0 0 50px -30px #000; padding: 40px; ">
<h1>{{ object }} <span style="font-weight:normal">&ndash; medlemsoppdatering</span></h1>
<form method=post action="">
{% csrf_token %}
    <table style="float:left; max-width:400px;">
      <tr><td colspan=2><h2>Informasjon</h2>
        {{ form }}
        <tr><th>Lokallag:<td>{{ object.lokallag|default:"Ingen" }}<br> <span class=helptext>Kontakt oss for å byta</span>
    </table>

    <table style="float: left; max-width: 400px;">
      <tr><td colspan=2><h2>Kontaktinnstillingar</h2>
      <!--tr><td><label>post</label> <td>
      <input type=checkbox value=nt checked>Norsk Tidend
      <input type=checkbox value=mm checked>Motmæle
      <input type=checkbox value=post checked>Vanleg post

      <tr><td><label>epost</label> <td>
      <input type=checkbox value=nyhendebrev checked>Nyhendebrev
      <input type=checkbox value=admin checked>Administrativ
      <input type=checkbox value=lokallag checked>Lokallag

      <tr><td><label>telefon</label> <td>
      <input type=checkbox value=sms checked>SMS
      <input type=checkbox value=telefon checked>Ring-->

      <tr><td><label>post</label> <td><select name=val_post id=val_post>
      {% val_option object '' 'Ikkje Motmæle,Ikkje Norsk Tidend' %}
        Motmæle, Norsk Tidend og post frå NMU
      {% val_option object 'Ikkje Norsk Tidend' 'Ikkje Motmæle' %}
        Motmæle og post frå NMU
      {% val_option object 'Ikkje Motmæle' 'Ikkje Norsk Tidend' %}
        Norsk Tidend og post frå NMU
      {% val_option object 'Ikkje Motmæle,Ikkje Norsk Tidend' '' %}
        Post frå NMU
      </select>

      <tr><td><label>telefon</label> <td><select name=val_tlf id=val_tlf>
      {% val_option object '' 'Ikkje ring,Ikkje SMS' %}
        Ring og SMS
      {% val_option object 'Ikkje ring' 'Ikkje SMS' %}
        Berre SMS
      {% val_option object 'Ikkje SMS' 'Ikkje ring' %}
        Berre ring
      {% val_option object 'Ikkje ring,Ikkje SMS' '' %}
        Ingen telefonbruk
      </select>

      {% comment %}
      <tr><td><label>epost</label> <td><select name=val_epost id=val_epost>
      {% val_option object '' 'Ikkje epost,Ikkje lokallagsepost' %}
        Frå lokallag og NMU
      {% val_option object 'Ikkje epost' 'Ikkje lokallagsepost' %}
        Frå lokallag
      {% val_option object 'Ikkje lokallagsepost' 'Ikkje epost' %}
        Frå NMU
      {% val_option object 'Ikkje epost,Ikkje lokallagsepost' '' %}
        Ingen epost
      {% endcomment %}
      <tr><td><td>
      <label><input type=checkbox name=val_nyhendebrev {% val_checked object 'Ikkje nyhendebrev' %} value='Ikkje nyhendebrev'>Ikkje motta nyhendebrev (eit par gongar i året)</label>

    </table>
    <div style="width:100%; clear:both; margin-bottom:20px;"></div>
    <input type=submit value=Endra>
</form>
{% for r in object.lokallagsrolle.all %}
<h2>{{ r }}</h2>
<p>Sidan du har ei rolle i {{ r }}, so kan du sjå medlemslistene til {{ r }}.
<p><a href='{{ r.listing }}?user_id={{ object.id }}&nykel={{ object.nykel }}'>Lokallagslister for {{ r }}</a>
{% endfor %}
</div>
{% endblock %}

medlemssys/templates/medlem/ringjeliste.html
{% extends "base.html" %}
{% load utils %}

{% block content %}
<style type=text/css>
    body { font: normal 0.8em sans-serif;}
    thead { background-color: #333; color: #eee; }
    th, td { padding: 4px; }
    tr:nth-child(even) { background-color: #eee; }
    table { width: 100%; }
</style>
<style type=text/css media=screen>
    h1 { border-bottom: 1px solid #000; margin-top: 3em; }
</style>
{% for llag in lokallag %}
{% ifchanged llag.andsvar %}
{% if not forloop.first %}</section>{%endif%}
<section><h1>{{ llag.andsvar }}</h1>{% endifchanged %}
<h2>{{ llag }}</h2>
    <table>
        <thead><tr>
                <th>ID</th>
                <th>Namn</th>
                <th>Født</th>
                <th>mob/tlf</th>
                <th>Postadr</th>
                <th>Epost</th>
                <th>bet</th>
            </tr>
        </thead>
      <tbody>
  {% for m in llag.medlem_set.interessante %}
          <tr>
            <td>{{ m.pk }}</td>
            <td>{{ m }}</td>
            <td>{{ m.fodt }}</td>
	    <td>{% val_exists m 'Ikkje ring' %} {{ m.mobnr }}{% if m.heimenr %}, {{ m.heimenr }}{% endif %}</td>
            <td>{{ m.postadr }}, {{ m.postnr }} {{ m.stad }}</td>
            <td>{{ m.epost }}</td>
            <td>{{ m.har_betalt|yesno:"b,ub,?" }} </td>
          </tr>
  {% endfor %}
        </tbody>
      </table>
{% endfor %}

{% endblock %}

medlemssys/templates/medlem/search.html
<!DOCTYPE html>
<meta charset=utf-8>
<title>Medlemsreg søk</title>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

<style type=text/css>
    body { font: normal 0.8em sans-serif;}
    thead { background-color: #333; color: #eee; }
    th, td { padding: 4px; }
    tr:nth-child(even) { background-color: #eee; }
    table { width: 100%; }
</style>

<div class="ui-widget">
  <form>
  <label for="members">Søk etter medlem: </label>
  <input id="members">
  </form>
</div>

<table>
<thead>
  <tr><th>Namn</th> <th>Betaling</th> <th>Lag</th></tr>
</thead>
<tbody>
  <tr><td>gjer eit søk</td> <td></td><td></td></tr>
</tbody>
</table>

<script>
var member_input = document.querySelector("#members");
var table = document.querySelector("table");
var xhr = new XMLHttpRequest();
var info = {};
var change_grace;

member_input.addEventListener('input', change)
//member_input.addEventListener('blur', change)
//member_input.addEventListener('change', change)

function change(e) {
    clearTimeout(change_grace);
    if (member_input.value.length < 3)
        return;

    change_grace = setTimeout(do_xhr, 500);
}

function do_xhr() {
    console.log("Doing XHR for " + member_input.value);
    xhr.open('GET', '/api/get_members.json?term=' + encodeURIComponent(member_input.value));
    xhr.onload = function(e) {
        console.log("Got resp: " + xhr.responseText);
        info = JSON.parse(xhr.responseText);
        build_table(info);
    }
    xhr.send();
}

function build_table(members) {
    var tableinfo = "";
    members.forEach(function(l) {
        tableinfo += "<tr>"
                 + "<td><a href='/admin/medlem/medlem/" + l.id + "/'>"
                 + l.namn + "</a> (" + l.alder + ")</td>"
                 + "<td>" + (''+l.bet).replace(/,/g, ', ') + "</td>"
                 + "<td>" + l.lokallag + "</td></tr>";
    });
    table.tBodies[0].innerHTML = tableinfo;
}
</script>
<div id=log></div>
{#% endblock content %#}